name: Build
on:
    workflow_dispatch:
jobs:
    raw:
        runs-on: ubuntu-latest
        container:
            image: sndevelopment/llvm-prepo:latest
            options: -u 0

        steps:
            - name: Install Git
              run: |
                  apt-get update
                  apt-get install -y git

            - uses: actions/checkout@v2

            - name: Build
              shell: bash
              run: |
                  cd "$GITHUB_WORKSPACE/raw"
                  make
                  ./a.out

    c:
        runs-on: ubuntu-latest
        container:
            image: sndevelopment/llvm-prepo:latest
            options: -u 0

        steps:
            - name: Install Git
              run: |
                  apt-get update
                  apt-get install -y git

            - uses: actions/checkout@v2

            - name: Build
              shell: bash
              run: |
                  cd "$GITHUB_WORKSPACE/c"
                  make
                  ./a.out hello world

    cxx:
        runs-on: ubuntu-latest
        container:
            image: sndevelopment/llvm-prepo:latest
            options: -u 0

        steps:
            - name: Install Git
              run: |
                  apt-get update
                  apt-get install -y git

            - uses: actions/checkout@v2

            - name: Build
              shell: bash
              run: |
                  cd "$GITHUB_WORKSPACE/cxx"
                  make
                  ./hello
